"""uom_model_creation

Revision ID: b7c55606fbd2
Revises: 9b1c9614e112
Create Date: 2024-07-19 14:31:07.015302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7c55606fbd2"
down_revision: Union[str, None] = "9b1c9614e112"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uoms",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("short_title", sa.String(length=10), nullable=False),
        sa.Column("full_title", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uoms")),
        sa.UniqueConstraint("full_title", name=op.f("uq_uoms_full_title")),
        sa.UniqueConstraint("short_title", name=op.f("uq_uoms_short_title")),
    )
    op.create_index(op.f("ix_uoms_id"), "uoms", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_uoms_id"), table_name="uoms")
    op.drop_table("uoms")
    # ### end Alembic commands ###
