"""Task model creation

Revision ID: 180415d3eca3
Revises: 4572720614c0
Create Date: 2024-07-24 01:35:20.152392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "180415d3eca3"
down_revision: Union[str, None] = "4572720614c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "creation_date",
            sa.DateTime(),
            server_default="2024-07-23 22:35:19.932106",
            nullable=False,
        ),
        sa.Column("start_value", sa.Float(), server_default="0", nullable=False),
        sa.Column("goal_value", sa.Float(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("finish_date", sa.DateTime(), nullable=True),
        sa.Column("folder_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            "start_value >= 0 AND goal_value >= 0",
            name=op.f("ck_tasks_non_negative_values"),
        ),
        sa.ForeignKeyConstraint(
            ["folder_id"], ["folders.id"], name=op.f("fk_tasks_folder_id_folders")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_tasks_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        sa.UniqueConstraint("title", name=op.f("uq_tasks_title")),
    )
    op.create_index(op.f("ix_tasks_id"), "tasks", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_id"), table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
