"""folder_model_creation

Revision ID: 4572720614c0
Revises: b7c55606fbd2
Create Date: 2024-07-19 22:31:05.354513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4572720614c0'
down_revision: Union[str, None] = 'b7c55606fbd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tasks_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('creation_date', sa.DateTime(), server_default='2024-07-19 19:31:05.144512', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('tasks_quantity >= 0', name=op.f('ck_folders_check_tasks_quantity_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_folders_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_folders')),
    sa.UniqueConstraint('title', name=op.f('uq_folders_title'))
    )
    op.create_index(op.f('ix_folders_id'), 'folders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_folders_id'), table_name='folders')
    op.drop_table('folders')
    # ### end Alembic commands ###
